[package]
name = "apksule"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
apksule-apk.workspace = true
apksule-runtime.workspace = true
rfd.workspace = true
self-replace = "1.5.0"
semver = "1.0.28"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
softbuffer.workspace = true
thiserror.workspace = true
tiny-skia.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ureq = { version = "3.3.0", features = ["json"] }
winit.workspace = true

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"

[target."cfg(windows)".build-dependencies]
winres = "0.1.12"
